table <- read.table('C:/Users/phani/Desktop/Coursera/Exploratory Data Analysis/Week 1/exdata%2Fdata%2Fhousehold_power_consumption/household_power_consumption.txt',sep=";",nrows= 2075260, header=TRUE, quote= "", strip.white=TRUE, stringsAsFactors = FALSE, na.strings= "?")
twodate<- subset(table, (table$Date == "1/2/2007" | table$Date== "2/2/2007"))
twodate$Date <- as.Date(twodate$Date, format = "%d/%m/%Y")
datetime <- as.POSIXct(paste(twodate$Date, twodate$Time))
png("plot3.png", width = 480, height = 480)
plot(datetime,twodate$Sub_metering_1, type="l", ylab= "Energy sub metering", xlab="")
lines(datetime, twodate$Sub_metering_2, type="l", col="red")
lines(datetime, twodate$Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"))
dev.off()